const lang = {
  en: {
    search: "Search",
    gptSearchPlaceholder: "What do you want to watch today?",
    allCategories: "Browse All Genre",
    top250: "Top 250",
    action: "Action",
    comedy: "Comedy",
    documentary: "Documentary",
    fantasy: "Fantasy",
    horror: "Horror",
    mystery: "Mystery",
    romance: "Romance",
    thriller: "Thriller",
    musical: "Musical",
  },
  hindi: {
    search: "खोज",
    gptSearchPlaceholder: "आज आप क्या देखना चाहेंगे?",
    allCategories: "सभी प्रकार ब्राउज़ करें",
    top250: "शीर्ष 250",
    action: "ऐक्शन",
    comedy: "कॉमेडी",
    documentary: "डॉक्यूमेंट्री",
    fantasy: "कल्पना",
    horror: "डरावने",
    mystery: "रहस्यमय",
    romance: "रोमांस",
    thriller: "थ्रिलर",
    musical: "संगीतमय",
  },
  bahasa: {
    search: "Mencari",
    gptSearchPlaceholder: "Apa yang ingin Anda tonton hari ini?",
    allCategories: "Jelajahi semua genre",
    top250: "250 teratas",
    action: "Tindakan",
    comedy: "Komedi",
    documentary: "Dokumenter",
    fantasy: "Fantasi",
    horror: "Fengerian",
    mystery: "Misteri",
    romance: "Romantis",
    thriller: "Thriller",
    musical: "Musikal",
  },
};

export default lang;
